import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Content, Header } from "antd/es/layout/layout";
import SideBar from "@/components/layout/sider";
import { Layout } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{minWidth:1400}}
      >
        <Layout style={{minHeight:"100vh"}}>
          <SideBar/>
          <Content>
            <section style={{padding: 15}}>
                  {children}
            </section>
          </Content>
        </Layout>

      </body>
    </html>
  );
}
